version: "3.9"

services:
  backend:
    build: .
    container_name: adocao_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app

  postgres:
    image: postgres:16
    container_name: adocao_db
    restart: always
    environment:
      POSTGRES_DB: adocao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: adocao_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@adocao.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
